import {
	Document,
	Page,
	Text,
	View,
	StyleSheet,
	Font,
} from "@react-pdf/renderer";

Font.register({
	family: "Inter",
	fonts: [
		{
			src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2",
			fontWeight: "normal",
		},
		{
			src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5n.woff2",
			fontWeight: "bold",
		},
	],
});

const styles = StyleSheet.create({
	page: {
		padding: 40,
		fontSize: 11,
		fontFamily: "Inter",
		lineHeight: 1.4,
	},
	title: {
		fontSize: 24,
		marginBottom: 8,
		fontWeight: "bold",
		textAlign: "center",
		color: "#1f2937",
	},
	description: {
		fontSize: 12,
		fontStyle: "italic",
		textAlign: "center",
		marginBottom: 24,
		color: "#4b5563",
	},
	section: {
		marginBottom: 20,
	},
	heading: {
		fontSize: 14,
		marginBottom: 8,
		fontWeight: "bold",
		color: "#ea580c",
		borderBottomWidth: 1,
		borderBottomColor: "#fed7aa",
		paddingBottom: 4,
	},
	metaRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 6,
		color: "#374151",
	},
	listItem: {
		marginBottom: 4,
		flexDirection: "row",
		alignItems: "flex-start",
	},
	bullet: {
		width: 12,
		color: "#ea580c",
	},
	instructionStep: {
		marginBottom: 10,
	},
	stepNumber: {
		fontWeight: "bold",
		fontSize: 12,
	},
	stepTitle: {
		fontWeight: "bold",
		marginBottom: 4,
	},
	divider: {
		height: 1,
		backgroundColor: "#e5e7eb",
		marginVertical: 16,
	},
	text: {
		marginBottom: 4,
	},
	footer: {
		position: "absolute",
		bottom: 30,
		left: 40,
		right: 40,
		textAlign: "center",
		fontSize: 9,
		color: "#9ca3af",
	},
	metaLabel: {
		fontWeight: "bold",
	},
});

export function RecipePDF({ recipe }) {
	const totalTime =
		parseInt(recipe.prepTime || 0) + parseInt(recipe.cookTime || 0) ||
		"N/A";

	return (
		<Document>
			<Page size="A4" style={styles.page}>
				{/* Header / Title */}
				<Text style={styles.title}>
					{recipe.title || "Untitled Recipe"}
				</Text>
				{recipe.description && (
					<Text style={styles.description}>{recipe.description}</Text>
				)}

				{/* Meta Info */}
				<View style={styles.section}>
					<View style={styles.metaRow}>
						<Text>
							<Text style={styles.metaLabel}>Cuisine:</Text>{" "}
							{recipe.cuisine || "—"}
						</Text>
						<Text>
							<Text style={styles.metaLabel}>Category:</Text>{" "}
							{recipe.category || "—"}
						</Text>
					</View>
					<View style={styles.metaRow}>
						<Text>
							<Text style={styles.metaLabel}>Total Time:</Text>{" "}
							{totalTime} mins
						</Text>
						<Text>
							<Text style={styles.metaLabel}>Servings:</Text>{" "}
							{recipe.servings || "—"}
						</Text>
					</View>
				</View>

				<View style={styles.divider} />

				{/* Ingredients */}
				<View style={styles.section}>
					<Text style={styles.heading}>Ingredients</Text>
					{recipe.ingredients?.length > 0 ? (
						recipe.ingredients.map((ing, i) => (
							<View key={i} style={styles.listItem}>
								<Text style={styles.bullet}>• </Text>
								<Text>
									{ing.item} —{" "}
									<Text style={{ fontWeight: "bold" }}>
										{ing.amount}
									</Text>
								</Text>
							</View>
						))
					) : (
						<Text style={{ color: "#9ca3af" }}>
							No ingredients listed
						</Text>
					)}
				</View>

				<View style={styles.divider} />

				{/* Instructions */}
				<View style={styles.section}>
					<Text style={styles.heading}>Instructions</Text>
					{recipe.instructions?.length > 0 ? (
						recipe.instructions.map((step) => (
							<View
								key={step.step}
								style={styles.instructionStep}
							>
								<Text>
									<Text style={styles.stepNumber}>
										{step.step}.
									</Text>{" "}
									<Text style={styles.stepTitle}>
										{step.title}
									</Text>
								</Text>
								<Text style={{ marginLeft: 16 }}>
									{step.instructions}
								</Text>
							</View>
						))
					) : (
						<Text style={{ color: "#9ca3af" }}>
							No instructions provided
						</Text>
					)}
				</View>

				{/* Tips */}
				{recipe.tips?.length > 0 && (
					<>
						<View style={styles.divider} />
						<View style={styles.section}>
							<Text style={styles.heading}>Chef's Tips</Text>
							{recipe.tips.map((tip, i) => (
								<View key={i} style={styles.listItem}>
									<Text style={styles.bullet}>• </Text>
									<Text>{tip}</Text>
								</View>
							))}
						</View>
					</>
				)}

				{/* Footer */}
				<Text style={styles.footer}>
					Generated by AI Chef • {new Date().toLocaleDateString()} •
					For personal use
				</Text>
			</Page>
		</Document>
	);
}
